name: Deploy (preview)

on:
  push:
    branches:
      - next

env:
  NEXT_PUBLIC_DEPLOYMENT_URL: https://preview.francoisbest.com
  NEXT_PUBLIC_CHIFFRE_PROJECT_ID: FMMnKLEnj2CDsV9g
  NEXT_PUBLIC_CHIFFRE_PUBLIC_KEY: pk.uuA8_Fy3voi1geHuJa6Z3Phg1JZQxDYvphH4MhTcsgg

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: 14.x
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        name: Load Next.js cache
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
        name: Install dependencies
      - run: yarn build:tools
        name: Build tools
      - run: yarn fetch
        name: Fetch static data
        env:
          SPOTIFY_CLIENT_ID:            ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET:        ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_CLIENT_REFRESH_TOKEN: ${{ secrets.SPOTIFY_CLIENT_REFRESH_TOKEN }}
          TWITTER_API_KEY:              ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY:       ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN:         ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          UNSPLASH_ACCESS_KEY:          ${{ secrets.UNSPLASH_ACCESS_KEY }}
          UNSPLASH_SECRET_KEY:          ${{ secrets.UNSPLASH_SECRET_KEY }}
          GITHUB_TOKEN:                 ${{ secrets.GITHUB_TOKEN }}
      - run: yarn build:next
        name: Build Next.js
        env:
          READING_LIST_CSV_URL:         ${{ secrets.READING_LIST_CSV_URL }}
      - run: cp -f ./public/robots.disallow.txt ./public/robots.txt
        name: Disable crawlers on Preview
      - run: yarn export
        name: Export static HTML/CSS/JS
      - uses: dswistowski/surge-sh-action@341bcbd76a97da5e6b55ad92f53c0bf840e04c80
        name: Publish to Surge
        with:
          domain: ${{ env.NEXT_PUBLIC_DEPLOYMENT_URL }}
          project: ./out
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - uses: 8398a7/action-slack@44a35a96508f31f916f99ad5b68f489ae45659a2
        name: Notify on Slack
        if: always() # Pick up events even if the job fails or is canceled.
        with:
          status: ${{ job.status }}
          author_name: Deployed to ${{ env.NEXT_PUBLIC_DEPLOYMENT_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
